export const constants = {
    TURN_ON: 'TURN_ON',
    TURN_OFF: 'TURN_OFF',
    SET_LFO_FREQUENCY: 'SET_LFO_FREQUENCY',
    SET_LFO_INTENSITY: 'SET_LFO_INTENSITY',
    SET_LFO_SHAPE: 'SET_LFO_SHAPE',
    SET_OSC_GAIN: 'SET_OSC_GAIN',
    SET_OSC_FREQUENCY: 'SET_OSC_FREQUENCY',
    SET_VCF_CUTOFF: 'SET_VCF_CUTOFF',
    SET_DELAY_TIME: 'SET_DELAY_TIME',
    SET_DELAY_FEEDBACK: 'SET_DELAY_FEEDBACK',
    SET_VOLUME: 'SET_VOLUME'
};
